### ISSUE TITLE
大佬能增加CdcAcm驱动吗？

### ISSUE THREAD

**Issue by bbfoxx** [LUJIAN2020/UsbSerialForAndroid.Net#4]
实在看不懂MauiUsbSerialForAndroid那个项目，感觉有点bug

**Comment by LUJIAN2020** [comment]
开了一个新的分支，看明天有没有时间了去完成，但我没有设备测试，能告诉我你的设备vid和pid吗？完成了通知你拉分支麻烦测试。

**Comment by LUJIAN2020** [comment]
https://github.com/LUJIAN2020/UsbSerialForAndroid.Net/tree/cdc-acm 可以进行测试

**Comment by LUJIAN2020** [comment]
> 实在看不懂MauiUsbSerialForAndroid那个项目，感觉有点bug

测试完记得告诉我一下
