### ISSUE TITLE
大神，每次USB设备插入，都会提示授权，能否相同设备只授权一次

### ISSUE THREAD

**Issue by willhuo** [LUJIAN2020/UsbSerialForAndroid.Net#9]
设备信息能看到
pid=29987
vid=6790

每次弹出授权窗口，我勾选了那个默认，但是下次插入相同的USB串口外设，还是会提示要授权。

跪求大佬给个答复

**Comment by LUJIAN2020** [comment]
这个是android的权限机制，应该是没办法的

**Comment by willhuo** [comment]
问题已经解决
